name: Actividad04 - PackageNuGet
env:
  DOTNET_VERSION: '8.0' # la versión de .NET
  SONAR_ORG: 'lab01calidadsoftware' # Nombre de la organización de SonarCloud
  SONAR_PROJECT: 'Brunoenr02_lab03calidadsoftware' # Key ID del proyecto de SonarCloud
  NUGET_PROJECT: 'Bank.WebApi'
  NUGET_OUTPUT_DIR: './nupkg'
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: snyk/actions/setup@master
    
    - name: Configurando la versión de .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install SonarScanner
      run: dotnet tool install -g dotnet-sonarscanner
    
    - name: Restore dependencies
      run: dotnet restore "Bank/Bank.sln"
    
    - name: Begin SonarCloud analysis
      run: |
        dotnet-sonarscanner begin \
          /k:"${{ env.SONAR_PROJECT }}" \
          /o:"${{ env.SONAR_ORG }}" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" \
          /d:sonar.qualitygate.wait=true \
          /d:sonar.exclusions="**/Program.cs,**/code-test-results.html,**/*.html"
    
    - name: Run tests with coverage
      run: dotnet test "Bank/Bank.sln" --collect:"XPlat Code Coverage;Format=opencover"
   
    - name: Build solution
      run: dotnet build "Bank/Bank.sln" --no-restore --configuration Release
    
    - name: End SonarCloud analysis
      run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

    # Crear el directorio 'nupkg' en caso de que no exista
    - name: Crear directorio de salida para NuGet
      run: mkdir -p ${{ env.NUGET_OUTPUT_DIR }}

    # Empaquetar el proyecto NuGet
    - name: Pack NuGet package
      run: |
        dotnet pack "Bank/${{ env.NUGET_PROJECT }}/${{ env.NUGET_PROJECT }}.csproj" \
          --configuration Release \
          --output ${{ env.NUGET_OUTPUT_DIR }}
    
    # Verificar que el paquete se haya generado correctamente
    - name: Verificar archivos generados en nupkg
      run: ls -la ${{ env.NUGET_OUTPUT_DIR }}

    # Publicar el paquete NuGet a GitHub Packages
    - name: Publish NuGet package to GitHub Packages
      run: | 
        dotnet nuget push "${{ env.NUGET_OUTPUT_DIR }}/*.nupkg" \
          --source "https://nuget.pkg.github.com/Brunoenr02/index.json" \
          --api-key "${{ secrets.GHTOKEN }}" \
          --skip-duplicate
