name: Actividad04 - NuGetPackage

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOTNET_VERSION: '8.x'
  PROJECT_PATH: './Bank.WebApi/Bank.WebApi.csproj'

jobs:
  build-test-analyze-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Navigate to Bank folder
        run: cd ./Bank

      - name: Verify current directory
        run: pwd

      - name: List files in Bank directory (Debugging)
        run: ls -la

      - name: Restore dependencies
        run: dotnet restore ./Bank.sln
        working-directory: ./Bank

      - name: Run tests and generate code coverage
        run: |
          dotnet test ./Bank.sln --collect:"XPlat Code Coverage"
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator \
            -reports:**/coverage.cobertura.xml \
            -targetdir:coveragereport \
            -reporttypes:MarkdownSummaryGithub
        working-directory: ./Bank

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./Bank/coveragereport

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./Bank
        env:
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build the NuGet package
        run: dotnet pack ${{ env.PROJECT_PATH }} -c Release -o ./nuget
        working-directory: ./Bank

      - name: Publish package to GitHub Packages
        run: dotnet nuget push ./nuget/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./Bank

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: NuGet Package
          path: ./Bank/nuget/*.nupkg
