name: Actividad03 - DocFX Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Add DocFX to PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore & Build Project
        working-directory: ./Bank
        run: |
          dotnet restore
          dotnet build

      - name: Generate Metadata
        working-directory: ./Bank
        run: docfx metadata docfx.json

      - name: Build Documentation Site
        working-directory: ./Bank
        run: docfx build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Bank/_site
