name: Release Version to GitHub

on:
  push:
    tags:
      - 'v*'  # Se ejecuta cuando haces push de un tag como v1.0.0, v1.2.3, etc.

env:
  DOTNET_VERSION: '8.0'
  NUGET_PROJECT: 'Bank.WebApi'
  NUGET_OUTPUT_DIR: './nupkg'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore "Bank/Bank.sln"

    - name: Run unit tests
      run: dotnet test "Bank/Bank.sln" --configuration Release

    - name: Pack NuGet package
      run: |
        mkdir -p ${{ env.NUGET_OUTPUT_DIR }}
        dotnet pack "Bank/${{ env.NUGET_PROJECT }}/${{ env.NUGET_PROJECT }}.csproj" \
          --configuration Release \
          --output ${{ env.NUGET_OUTPUT_DIR }}

    - name: List generated .nupkg files
      run: ls -la ${{ env.NUGET_OUTPUT_DIR }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.NUGET_OUTPUT_DIR }}/*.nupkg
      env:
        GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
