name: Actividad02 - Semgrep Analysis
env:
  DOTNET_VERSION: '8.x'  # La versión de .NET
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  security:
    runs-on: ubuntu-latest
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Semgrep
        run: |
          python -m pip install semgrep
          python -m pip install prospector2html

      - name: Run Semgrep scan
        run: |
          semgrep scan --config="p/default" --json --output semgrep.json

      - name: Generate HTML report with prospector2html
        run: |
          prospector-html --input semgrep.json --output semgrep-report.html --filter semgrep

      - name: Upload the Semgrep HTML report to GitHub Pages
        run: |
          mkdir -p docs
          mv semgrep-report.html docs/
        # Configura el despliegue a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
