name: Actividad02 - Semgrep Analysis
env:
  DOTNET_VERSION: '8.x'  # La versión de .NET

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  security:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep  # Docker con Semgrep instalado

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Python, create virtual environment, and install pip
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip

      - name: Install Semgrep
        run: |
          . venv/bin/activate
          pip install semgrep

      - name: Install prospector2html
        run: |
          . venv/bin/activate
          pip install prospector2html

      - name: Install prospector-html
        run: |
          . venv/bin/activate
          pip install prospector-html
      
      - name: Run Semgrep scan and generate HTML report
        run: |
          . venv/bin/activate
          semgrep scan --config="p/default" --json --output semgrep.json
          # Convertir el reporte JSON a HTML
          python3 -m json.tool semgrep.json > semgrep.html
      
      - name: (T2) Convert JSON to HTML using prospector-html
        run: |
          prospector-html semgrep.json > semgrep-prospector.html

      - name: Upload reports to GitHub Pages
        run: |
          mkdir -p docs
          mv semgrep.json docs/
          mv semgrep.html docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
