name: Actividad02 - Semgrep Analysis
env:
  DOTNET_VERSION: '8.x'  # La versión de .NET
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  security:
    runs-on: ubuntu-latest
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Python, create virtual environment, and install pip
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip

      - name: Install Semgrep
        run: |
          . venv/bin/activate
          pip install semgrep

      - name: Run Semgrep scan
        run: |
          . venv/bin/activate
          semgrep scan --config="p/default" --json --output semgrep.json

      - name: Upload the Semgrep JSON report to GitHub Pages
        run: |
          mkdir -p docs
          mv semgrep.json docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
